INSERT INTO labanalysis(sample_id,
                        title,
                        description,
                         priority,
                          email,
                           analysis_status,
                           analysis_run_number,
                           analysis_start,
                           analysis_end) VALUES (13,
                            "This is a sample Title",
                             "This is a sample description",
                              3,
                               "customer@google.com",
                                "STATUS-STARTED",
                                1,
                                "2017-05-20T12:03:02.200",
                                 "2017-05-20T17:03:02.200");

INSERT INTO labanalysis(sample_id,
                        title,
                        description,
                         priority,
                          email,
                           analysis_status,
                           analysis_run_number,
                           analysis_start,
                           analysis_end) VALUES (14,
                            "This is a sample Title2",
                             "This is a sample description2",
                              2,
                               "customer@fit.com",
                                "STATUS-STARTED",
                                1,
                                "2017-05-21T14:03:02.200",
                                 "2017-05-21T16:03:02.200");

